# Generated by Django 5.1 on 2024-08-31 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Email Account',
            },
        ),
        migrations.CreateModel(
            name='EmailMassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='зоголовок')),
                ('body', models.TextField(verbose_name='тело письма')),
                ('sent_date', models.DateTimeField()),
                ('received_date', models.DateTimeField()),
                ('attachments', models.JSONField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='parsers.emailaccount')),
            ],
            options={
                'verbose_name': 'Email Massage',
                'verbose_name_plural': 'Email Massages',
            },
        ),
    ]
